server {
	listen 443 ssl;#ipv4, no http, only ssl
	listen [::]:443 ssl; #ipv6
	server_name vcaratti.42.fr;
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_certificate /etc/ssl/certs/inception.crt;
	ssl_certificate_key /etc/ssl/private/inception.key;

	root /var/www/html;
	index index.php index.html;

	location / {
		try_files $uri $uri/ /index.php$is_args$args;	#safe fallback, php std. calls to fallback to index.php with args
	}
	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass wordpress:9000;			#forwarding to wordpress container
		fastcgi_index index.php;		#convention but not nescessary
		include fastcgi_params; 		#needed for cgi, query + 'headers'

		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; 	#root + script
		fastcgi_param PATH_INFO $fastcgi_path_info;				#niche cases, from split_path_info
	}
}
